[build]
  base    = ""
  publish = "/build"
  command = "yarn build --type=UMD_DEV && cd fixtures/dom/ && yarn && yarn prestart && yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200